"""add user_id foreign key to employees

Revision ID: 6a4d3bed9dc0
Revises: 68045d6c0786
Create Date: 2026-09-11 09:04:20.033129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4d3bed9dc0'
down_revision: Union[str, Sequence[str], None] = '68045d6c0786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'employees', ['user_id'])
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
